about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('impressum/', views.ImpressumView.as_view(), name='impressum'),
]

barrierefreieapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('welcome.urls')),
    path('welcome/', include('welcome.urls')),
    path('about/', include('about.urls')),
    path('wiki/', include('wiki.urls')),
    path('checklist/', include('checklist.urls')),
    path('admin/', admin.site.urls),
]

checklist/urls.py
from django.urls import path

from . import views

app_name = 'checklist'
urlpatterns = [path('', views.IndexView.as_view(), name='index')]

welcome/urls.py
from django.urls import path

from . import views

app_name = 'welcome'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

wiki/urls.py
from django.urls import path

from . import views

app_name = 'wiki'
urlpatterns = [path('', views.IndexView.as_view(), name='index')]

about/models.py
from django.db import models

# Create your models here.

checklist/models.py
from django.db import models


class CheckListCategory(models.Model):
    """
    Model for checklist categories
    """
    wikiEntry = models.ForeignKey(
        'wiki.WikiEntry', on_delete=models.SET_NULL, blank=True, null=True)
    categoryTitle = models.CharField(max_length=100)

    def getEntries(self):
        return self.checklistentry_set.all()

    def __str__(self):
        return self.categoryTitle


class CheckListEntry(models.Model):
    """
    Model for checklist entries, severity describes the importance of an entry
    """
    checklistCategory = models.ForeignKey(
        'checklist.CheckListCategory', on_delete=models.SET_DEFAULT, default=1)
    wikiEntry = models.ForeignKey(
        'wiki.WikiEntry', on_delete=models.SET_NULL, blank=True, null=True)
    checkListEntryTitle = models.CharField(max_length=200)
    checkListEntrySeverity = models.CharField(max_length=10)
    checkListEntryDescription = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.checkListEntryTitle

    class Meta:
        ordering = ['-checkListEntrySeverity', 'checkListEntryTitle']

welcome/models.py
from django.db import models

# Create your models here.

wiki/models.py
from django.db import models


class WikiEntry(models.Model):
    """
    Model for wiki entries.
    allows queries for negative and positive examples.
    """
    wikiTitle = models.CharField(max_length=200)
    wikiText = models.TextField()

    def getPositiveExamples(self):
        return self.wikiexample_set.filter(examplePositive=True)

    def getNegativeExamples(self):
        return self.wikiexample_set.filter(examplePositive=False)

    def __str__(self):
        return self.wikiTitle

    class Meta:
        ordering = ['wikiTitle']


class WikiExample(models.Model):
    """
    Model for wiki example to be used for an wiki entry.
    """
    wikiEntry = models.ForeignKey(
        WikiEntry, on_delete=models.SET_NULL, null=True)
    exampleTitle = models.CharField(max_length=200)
    exampleText = models.TextField(default="Beispiel")
    exampleImage = models.CharField(max_length=200)
    exampleImageAlt = models.CharField(max_length=400, default="Bild")
    examplePositive = models.BooleanField(default=True)

    def __str__(self):
        return self.exampleTitle

    class Meta:
        ordering = ['-examplePositive', 'exampleTitle']

about/views.py
from django.views import generic


class IndexView(generic.TemplateView):
    """
    Default view for about page
    """
    template_name = 'about/index.html'


class ImpressumView(generic.TemplateView):
    """
    View class that loads the impressum
    """
    template_name = 'about/impressum.html'

checklist/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic

from .models import CheckListCategory


class IndexView(generic.ListView):
    """
    Default view for checklist page.
    Passes date from models to checklist template.
    """
    template_name = 'checklist/index.html'
    context_object_name = 'checklist'

    def get_queryset(self):
        return CheckListCategory.objects.all()

welcome/views.py
from django.views import generic


class IndexView(generic.TemplateView):
    """
    Default view for welcome page
    """
    template_name = 'welcome/index.html'

wiki/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.db.models import Prefetch
from django.views import generic

from .models import  WikiEntry, WikiExample


class IndexView(generic.ListView):
    """
    Default view for wiki page.
    Passes data from wiki models to wiki template.
    """
    template_name = 'wiki/index.html'
    context_object_name = 'wiki_list'

    def get_queryset(self):
        return WikiEntry.objects.all()

about/templates/about/impressum.html
{% extends "base.html" %}

{% block title %}
{% with title="Impressum" %}
{{block.super}}
{% endwith %}
{% endblock %}

{% block content %}

<div class="grid-container">
	<div class="grid-x cell-background-lg">
		<div class="cell vertical-space">
			<h1>Impressum</h1>
		</div>
		<div class="cell">
			<ul class='no-bullet'>
				<li>Technische Hochschule Mittelhessen</li>
				<li>Wilhelm-Leuschner-Straﬂe 13</li>
				<li>61169 Friedberg (Hessen)</li>
				<li>Telefon: 06031 6040</li>
				<li>E-Mail: marc.ackermann@iem.thm.de</li>
			</ul>
		</div>
		<div class="cell">
			<ul class='no-bullet'>
				<li>Vertreten durch die Studierenden:</li>
				<li>Dennis Appel</li>
				<li>Marc Ackermann</li>
				<li>Selina G&ouml;rnert</li>
				<li>Jan Ilge</li>
			</ul>

		</div>
		<div class="cell">
			<h2>Rechtliche Hinweise</h2>
			<h3>&sect; 1 Inhaltliche Warnhinweise</h3>
			<p>
			Die kostenlosen und frei zug&auml;nglichen Informationen dieser Webportals wurden mit großm&ouml;glichster Sorgfalt erstellt. Es wird jedoch keine Gewahr f&uuml;r die Richtigkeit und Aktualit&auml;t der bereitgestellten kostenlosen und frei zug&auml;nglichen Eintr&auml;ge und Beispielen. Namentlich gekennzeichnete Beitr&auml;ge geben die Meinung des jeweiligen Autors und nicht immer die Meinung des Anbieters wieder.
			Allein durch den Aufruf der kostenlosen und frei zug&auml;nglichen Inhalte kommt keinerlei Vertragsverh&auml;ltnis zwischen dem Nutzer und dem Anbieter zustande, insoweit fehlt es am Rechtbindungswillen des Anbieters.
			</p>
			<h3>&sect; 2 Urheber- und Leistungsschutzrechte</h3>
			<p>
			Die auf diesem Webportal ver&ouml;ffentlichen Inhalte unterliegen dem deutschen Urheber- und Leistungsschutzrecht. Jede davon nicht zugelassene Verwertung bedarf der vorherigen schriftlichen Zustimmung des Anbieters. Dies gilt insbesondere f&uuml;r Vervielf&auml;ltigung, Bearbeitung, &Uuml;bersetzung, Einspeicherung und Verarbeitung. Die unerlaubte Vervielf&auml;ltigung oder Weitergabe kompletter Seiten ist nicht gestattet und strafbar.
			</p>
		</div>
		<div class="cell vertical-space-bottom">
			<h2>Quellen</h2>
			<ul>
				<li>
					<a class="link" href="https://pixabay.com/de/inklusion-gruppe-rollstuhl-2731343/">https://pixabay.com/de/inklusion-gruppe-rollstuhl-2731343/</a>
				</li>
				<li>
					<a class="link" href="https://www.w3.org/Translations/WCAG20-de/">https://www.w3.org/Translations/WCAG20-de/</a>
				</li>
				<li>
					<a class="link" href="https://www.funkschau.de/mobile-solutions/artikel/144958/">https://www.funkschau.de/mobile-solutions/artikel/144958/</a>
				</li>
				<li>
					<a class="link" href="https://www.youbility.de/blog/das-internet-ist-fur-alle-da-checkliste-zur-barrierefreiheit-von-webanwendungen/">https://www.youbility.de/blog/das-internet-ist-fur-alle-da-checkliste-zur-barrierefreiheit-von-webanwendungen/</a>
				</li>
				<li>
					<a class="link" href="http://www.leserlich.info/index.php">http://www.leserlich.info/index.php</a>
				</li>
				<li>
					<a class="link" href="https://www.barrierefreies-webdesign.de/richtlinien/wcag-2.0-deutsch-englisch/konformitaetsstufe.html">https://www.barrierefreies-webdesign.de/richtlinien/wcag-2.0-deutsch-englisch/konformitaetsstufe.html</a>
				</li>
				<li>
					<a class="link" href="https://www.bitfactory.io/de/blog/barrierefreie-apps/">https://www.bitfactory.io/de/blog/barrierefreie-apps/</a>
				</li>
				<li>
					<a class="link" href="https://www.marlem-software.de/marlemblog/2013/06/11/richtlinien-zur-barrierefreien-software-entwicklung-fur-java-von-ibm/">https://www.marlem-software.de/marlemblog/2013/06/11/richtlinien-zur-barrierefreien-software-entwicklung-fur-java-von-ibm/<Paste></a>
				</li>
				<li>
					<a class="link" href="http://www.di-ji.de">http://www.di-ji.de</a>
				</li>
				<li>
					<a class="link" href="https://www.einfach-fuer-alle.de/blog/id/2792/ ">https://www.einfach-fuer-alle.de/blog/id/2792/ </a>
				</li>
				<li>
					<a class="link" href="https://www.bundesfachstelle-barrierefreiheit.de/DE/Praxishilfen/Informationstechnik/Barrierefreie-Apps/barrierefreie-apps_node.html">https://www.bundesfachstelle-barrierefreiheit.de/DE/Praxishilfen/Informationstechnik/Barrierefreie-Apps/barrierefreie-apps_node.html</a>
				</li>
				<li>
					<a class="link" href="https://www.pctipp.ch/tipps-tricks/kummerkasten/multimedia/artikel/farben-fuer-farbenblinde-auswaehlen-81076/">https://www.pctipp.ch/tipps-tricks/kummerkasten/multimedia/artikel/farben-fuer-farbenblinde-auswaehlen-81076/</a>
				</li>
				<li>
					<a class="link" href="https://www.mytherapyapp.com/de/blog/barrierefreie-apps-technik">https://www.mytherapyapp.com/de/blog/barrierefreie-apps-technik</a>
				</li>
				<li>
					<a class="link" href="https://www.apple.com/de/accessibility/">https://www.apple.com/de/accessibility/</a>
				</li>
				<li>
					<a class="link" href="https://developer.apple.com/design/human-interface-guidelines/ios/overview/themes/">https://developer.apple.com/design/human-interface-guidelines/ios/overview/themes/</a>
				</li>
				<li>
					<a class="link" href="https://developer.android.com/guide/topics/ui/accessibility/">https://developer.android.com/guide/topics/ui/accessibility/</a>
				</li>
			</ul>
		</div>
	</div>
</div>

{% endblock %}

about/templates/about/index.html
{% extends "base.html" %}

{% block title %}
{% with title="Infos" %}
{{ block.super }}
{% endwith %}
{% endblock %}

{% block content %}
<div class="grid-container padding-bottom">
    <div class="grid-x">
        <div name="barrierefreiheit" id="barrierefreiheit" class="cell cell-background-lg vertical-space">
            <section>
                <h1>Was ist Barrierefreiheit?</h1>
                <p>
                Wenn man auf das Wort Barrierefreiheit st&ouml;&szlig;t, denkt
                man zuerst an Aufz&uuml;ge statt Treppen, breite T&uuml;ren und
                sonstige bauliche Ver&auml;nderungen im Alltag. Das stimmt auch.
                Barrierefreiheit bedeutet, dass Geb&auml;ude, &ouml;ffentliche
                Pl&auml;tze, Verkehrsmittel und vieles mehr, so gestaltet werden,
                dass sie f&uuml;r alle zug&auml;nglich sind, ohne, dass man auf a
                Hilfe von einer anderen Person angewiesen ist.<br>
                Hinter Barrierefreiheit steckt aber noch viel mehr. Texte sollten
                beispielsweise in einer einfach verst&auml;ndlichen Sprache
                formuliert sein und vielleicht noch mit Bildern untermauert werden,
                damit Menschen mit Lernschwierigkeiten diese auch verstehen k&ouml;nnen.
                Geh&ouml;rlose Menschen sollten Vortr&auml;ge verfolgen k&ouml;nnen,
                zum Beispiel mit Hilfe eines Geb&auml;rdendolmetschers oder
                Untertiteln, falls es sich um ein Video handelt. Barrierefreiheit
                ber&uuml;cksichtigt also menschliche F&auml;higkeiten in allen
                Auspr&auml;gungen.
                </p>
                <p>
                Am 1. Mai 2002 trat das Gesetz zur Gleichstellung von Menschen
                mit Behinderungen (BGG) in Kraft.<br>
                Barrierefreiheit wird in &sect; 4 BGG wie folgt definiert:
                <blockquote>
                    „Barrierefrei sind bauliche und sonstige Anlagen,
                    Verkehrsmittel, technische Gebrauchsgegenst&auml;nde,
                    Systeme der Informationsverarbeitung, akustische und visuelle
                    Informationsquellen und Kommunikationseinrichtungen sowie andere
                    gestaltete Lebensbereiche, wenn sie f&uuml;r Menschen mit
                    Behinderungen in der allgemein &uuml;blichen Weise, ohne
                    besondere Erschwernis und grunds&auml;tzlich ohne fremde
                    Hilfe auffindbar, zug&auml;nglich und nutzbar sind. Hierbei
                    ist die Nutzung behinderungsbedingt notwendiger Hilfsmittel
                    zul&auml;ssig.“
                </blockquote>
                Aber dann gibt es nat&uuml;rlich noch die digitale Barrierefreiheit.
                Das bedeutet, Internetseiten und Apps m&uuml;ssen so gestaltet
                sein, dass jeder sie nutzen kann. Und wie das funktioniert und
                was alles dazu geh&ouml;rt, wollen wir in diesem Infoportal
                erkl&auml;ren.
                </p>
            </section>
        </div>
        <div name="app" id="app" class="cell cell-background-lg vertical-space">
            <section>
                <h1>Wozu Barrierefreiheit?</h1>
                <p>
                Niemandem soll das Teilhaben am allt&auml;glichen Leben durch
                Barrieren verwehrt werden. Wie im Grundgesetz steht (Artikel 3,
                Absatz 3) „Niemand darf wegen seiner Behinderung benachteiligt
                werden.“<br>
                Barrierefreiheit hat f&uuml;r alle einen Nutzen, nicht nur f&uuml;r
                Menschen mit Behinderung, sondern auch Senioren oder Menschen,
                die nur vor&uuml;bergehend eine Einschr&auml;nkung haben. Zum Beispiel
                hilft ein Aufzug Eltern mit Kinderwagen, jemandem mit
                gebrochenem Bein oder einem &auml;lteren Menschen, der nicht mehr
                gut zu Fu&szlig; unterwegs ist. Alter und Behinderungen gehen oft
                einher: ca. ein Viertel der Menschen mit Schwerbehinderung ist
                75 Jahre und &auml;lter, die H&auml;lfte ist zwischen 55 und 75 Jahren
                alt. Die durchschnittliche Lebenserwartung steigt – ein Grund
                mehr, sich f&uuml;r ein Leben ohne Barrieren einzusetzen!
                </p>
            </section>
        </div>
    </div>
</div>
{% endblock %}

checklist/templates/checklist/index.html
{% extends "base.html" %}

{% block title %}
{% with title="Checkliste" %}
{{ block.super }}
{% endwith %}
{% endblock %}

{% block content %}
<section>
    {% if checklist %}
    <div class="grid-x grid-padding-x">

        <div class="cell large-offset-3 large-6 content vertical-space">
            <section>
            <h1>Checkliste</h1>
            <p>
            Die Checkliste dient der Selbstkontrolle zur Einhaltung der
            Barrierefreiheit.<br>
            Die Liste ist als Leitfaden w&auml;hrend der Entwicklung gedacht
            und beinhaltet von uns als besonders wichtig befundene und
            empfohlene Richtlinien.
            </p>
            <p>
            Ist eine Richtlinie implementiert, kann diese durch Verwendung des
            roten "Offen" Buttons auf abgeschlossen gesetzt werden. Sollte
            eine Richtlinie noch nicht vollst&auml;ndig implementiert sein,
            oder bedarf weiterer Arbeit, kann dieser Schritt mit Hilfe des nun
            gr&uuml;nen "Abgeschlossen" Buttons wieder r&uuml;ckg&auml;ngig
            gemacht werden.<br>
            Abgeschlossene Richtlinien werden im Local Storage des Browsers
            gespeichert, es kann also der Tab, oder Browser, ohne bedenken
            geschlossen werden. Beim erneuten Aufruf der Seite, werden diese
            Richtlinien automatisch auf "Abgeschlossen" gesetzt.
            </p>
            </section>
            <div id='checklist' class="grid-x grid-padding-x grid-padding-y grid-margin-y">
                {% for category in checklist %}
                <div class="cell cell-background-lg">
                    <div class="grid-x grid-padding-x">
                        <div class="cell" id="category_{{category.id}}" name="category_{{category.id}}">
                            <h2>{{category.categoryTitle}}</h2>
                            {% if category.wikiEntry.id %}
                            <a class="link" href="{% url 'wiki:index' %}#item_{{category.wikiEntry.id}}"><button class="hollow button">Wiki</button></a>
                            {% endif %}
                        </div>
                        {% for entry in category.getEntries %}
                        <div class="cell vertical-space-bottom-small" id="entry_{{entry.id}}" name="entry_{{entry.id}}">
                            <button class="button small alert checklist-entry" onclick="checkListToggle(this, {{entry.id}})">Offen
                            </button>
                            <h3 class="checklist-entry checklist-title">
                                {{entry.checkListEntryTitle}}
                                {% if entry.wikiEntry.id %}&nbsp;
                                <a class="link" href="{% url 'wiki:index' %}#item_{{entry.wikiEntry.id}}">&lt;Wiki&gt;</a>
                                {% endif %}
                            </h3>
                            <p>
                            {{entry.checkListEntryDescription}}
                            </p>
                        </div>
                        {% endfor %}
                        <div class="cell back-button">
                            <a class="link" href="#checklist-navigation"><button class="button hollow">nach oben</button></a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="cell large-2 large-offset-1 cell-background-wiki-mg wiki-navigation">
            <section>
                <div name="checklist-navigation" id="checklist-navigation" class="text-center">
                    <h4>Inhalt</h4>
                </div>
                <ul class="vertical menu">
                    {% for category in checklist %}
                    <li>
                        <a class="wiki-navigation-link" href="#category_{{category.id}}">{{category.categoryTitle}}</a>
                    </li>
                    {% endfor %}
                </ul>
            </section>
        </div>

    </div>
    {% else %}
    <p>Keine Eintraege gefunden</p>

    {% endif %}
</section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html class="no-js" lang="de">
    <head>
        {% load staticfiles %}
        <meta charset="utf-8" />
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% block title %}
        <title>{{title}} - Barrierefreie App</title>
        {% endblock %}
        <link rel="stylesheet" href="{% static 'css/app.css' %}" />
    </head>
    <body>
        <div class="main">
            {% block header %}{% endblock %}
            {% block navigation %}
            <section>
                <div class="top-bar">
                    <div class="top-bar-left">
                        <span class="banner-title">Webportal - ergonomische, mobile Anwendungen</span>
                    </div>
                    <div class="top-bar-right">
                        <nav>
                            <ul class="menu align-right middle">
                                <li class="menu-border-left"><a href="/welcome/">Start</a></li>
                                <li class="menu-border-left"><a href="/about/">Infos</a></li>
                                <li class="menu-border-left"><a href="/checklist/">Checkliste</a></li>
                                <li class="menu-border-left"><a href="/wiki/">Wiki</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </section>
            {% endblock %}
            {% block content %}{% endblock %}

            {% block footer %}
            <section>
                <div class="footer cell-background-mg">
                    <ul class="menu middle">
                        <li>
                            <a class="link" href="/about/impressum/">Impressum</a>
                        </li>
                    </ul>
                </div>
            </section>
            {% endblock %}
        </div>

        <script src="{% static 'node_modules/jquery/dist/jquery.js' %}"></script>
        <script src="{% static 'node_modules/what-input/dist/what-input.js' %}"></script>
        <script src="{% static 'node_modules/foundation-sites/dist/js/foundation.js' %}"></script>
        <script src="{% static 'js/app.js' %}"></script>
    </body>
</html>

templates/footer.html
{% load staticfiles %}
    <h1>FOOTER</h1>

    <script src="{% static 'project/node_modules/jquery/dist/jquery.js' %}"></script>
    <script src="{% static 'project/node_modules/what-input/dist/what-input.js' %}"></script>
    <script src="{% static 'project/node_modules/foundation-sites/dist/js/foundation.js' %}"></script>
    <script src="{% static 'project/js/app.js' %}"></script>
  </body>
</html>

templates/header.html
<!doctype html>
<html class="no-js" lang="en">
  <head>
      {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Foundation for Sites</title>
    <link rel="stylesheet" href="css/app.css">
  </head>
  <body>
<h1>HEADER</h1>

welcome/templates/welcome/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
{% with title="Startseite" %}
{{ block.super }}
{% endwith %}
{% endblock %}

{% block content %}
<section>
    <div class="banner">
        <img src="{% static 'images/inclusion_no_background.png' %}" alt="Banner Bild - zeigt Sillhouetten mehrerer Menschen verschiedener alters Gruppen mit und ohne Behinderung.">
    </div>
</section>
<section>
    <div class="grid-container vertical-space padding-bottom">
        <div class="grid-x grid-padding-x">
            <div class="cell cell-background-lg">
                <section>
                    <h2>Worum geht es?</h2>
                    <p>
                    Niemandem soll das Teilhaben am allt&auml;glichen Leben durch
                    Barrieren verwehrt werden. Wie im Grundgesetz steht
                    (Artikel 3, Absatz 3) „Niemand darf wegen seiner Behinderung
                    benachteiligt werden.“
                    </p>
                    <p>
                    Barrierefreiheit hat f&uuml;r alle einen Nutzen, nicht nur f&uuml;r
                    Menschen mit Behinderung, sondern auch Senioren oder Menschen,
                    die nur vor&uuml;bergehend eine Einschr&auml;nkung haben. Zum Beispiel
                    hilft ein Aufzug Eltern mit Kinderwagen, jemandem mit
                    gebrochenem Bein oder einem &auml;lteren Menschen, der nicht mehr
                    gut zu Fu&szlig; unterwegs ist. Alter und Behinderungen gehen oft
                    einher: ca. ein Viertel der Menschen mit Schwerbehinderung ist
                    75 Jahre und &auml;lter, die H&auml;lfte ist zwischen 55 und 75 Jahren
                    alt. Die durchschnittliche Lebenserwartung steigt – ein Grund
                    mehr, sich f&uuml;r ein Leben ohne Barrieren einzusetzen!
                    </p>
                </section>
            </div>
            <div class="cell cell-background-lg vertical-space">
                <section>
                    <h2>Was ist Barrierefreiheit?</h2>
                    <p>
                    Wenn man auf das Wort Barrierefreiheit st&ouml;&szlig;t, denkt man zuerst
                    an Aufz&uuml;ge statt Treppen, breite T&uuml;ren und sonstige bauliche
                    Ver&auml;nderungen im Alltag. Das stimmt auch. Barrierefreiheit
                    bedeutet, dass Geb&auml;ude, &ouml;ffentliche Pl&auml;tze, Verkehrsmittel und
                    vieles mehr, so gestaltet werden, dass sie f&uuml;r alle zug&auml;nglich
                    sind, ohne, dass man auf Hilfe von einer anderen Person
                    angewiesen ist.
                    </p>
                    <a href="/about/#barrierefreiheit"><button class="hollow button">Mehr erfahren</button></a>
                </section>
            </div>
        </div>
        <div class="grid-x grid-margin-x vertical-space">
            <div class="cell large-6 cell-background-lg">
                <section>
                    <h3>Was ist eine barrierefreie App?</h3>
                    <p>
                    Eine barrierefreie App ist ganz allgemein eine Applikation,
                    die f&uuml;r jeglichen Menschen zug&auml;nglich und nutzbar ist. Es
                    geht also nicht darum eine spezielle App f&uuml;r behinderte
                    Personen zu konstruieren, wie zum Beispiel eine Lese-App
                    f&uuml;r Blinde, sondern ganz einfach darum jede Art von
                    Applikation f&uuml;r jeden bedienbar zu gestalten.<br>
                    Dabei denkt man nat&uuml;rlich erst einmal an Sehbehinderte oder
                    Geh&ouml;rgesch&auml;digte, aber auch motorisch oder kognitiv
                    eingeschr&auml;nkte Menschen, sowie ganz einfach Leute, die
                    nicht mit diesem Programm vertraut sind, haben besondere
                    Bed&uuml;rfnisse, wenn es um die Nutzung von Apps geht.
                    Diese reichen von der Gr&ouml;&szlig;e der Buttons, &uuml;ber das richtige
                    Farbschema, bis hin zu einer geeigneten Schriftart oder
                    einer erh&ouml;hten Fehlertoleranz.
                    </p>
                    <a href="/about/#app"><button class="hollow button">Mehr erfahren</button></a>
                </section>
            </div>
            <div class="cell large-6 cell-background-lg">
                <section>
                    <h3>Wie mache ich eine barrierefreie App?</h3>
                    <p>
                    Wir bieten diverse Resourcen und Guidelines zum Erstellen
                    einer barrierefreien App.<br>
                    Das Wiki beschreibt allgemeine und App spezifische Guidelines
                    f&uuml;r Entwickler und erl&auml;tert diese anhand von
                    ausgew&auml;ten Beispielen.<br>
                    Die interaktive Checkliste soll Entwicklern dabei helfen,
                    w&auml;hrend der Entwicklung die von uns empfohlenen
                    Richtlinien effektiv umzusetzen.
                    </p>
                    <a href="/checklist/"><button class="hollow button">Zur Checkliste</button></a>
                    <a href="/wiki/"><button class="hollow button">Zum Wiki</button></a>
                </section>
            </div>
        </div>
    </div>

</section>

{% endblock %}